services:
  mysql:
    container_name: jwt_mysql
    image: "mysql:8.0.39-bookworm"
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
